name: 'yamlto-arm'
description: 'This GitHub action can be used to convert Microsoft Sentinel yaml files to deployable ARM templates'
branding:
  icon: 'check-square'
  color: 'green'
inputs:
  parameter1:
    description:  'filesPath'
    required: false
    default: ''
#   parameter1:
#     description:  'parameter 2 description'
#     required: false
#     default: ''

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/action.ps1 `
              -parameter1 '${{ inputs.parameter1 }}' `
#               -parameter2 '${{ inputs.parameter2 }}'
      shell: pwsh
