name: 'yamlto-arm'
description: 'This GitHub action can be used to convert Microsoft Sentinel yaml files to deployable ARM templates'
branding:
  icon: 'check-square'
  color: 'green'
inputs:
  filesPath:
    description:  'Path to source files'
    required: true
    default: ''
  outputPath:
    description:  'Path to destination'
    required: true
    default: ''
  singleFile:
    description:  'Output single deployment template'
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/action.ps1 `
              -FilesPath '${{ inputs.filesPath }}' `
              -OutputPath '${{ inputs.outputPath }}' `
              -SingleFile ${{ inputs.SingleFile }}
      shell: pwsh
