name: 'ymlto-arm'
description: 'This GitHub action can be used to convert Microsoft Sentinel yaml files to deployable ARM templates'
branding:
  icon: 'check-square'
  color: 'green'
inputs:
  filesPath:
    description:  'Path to source files'
    required: false
    default: ''
  outputPath:
    description:  'Path to destination'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/action.ps1 `
              -FilesPath '${{ inputs.filesPath }}' `
              -OutputPath '${{ inputs.outputPath }}'
      shell: pwsh
